server:
  port: ":8443"
  path_to_certfile: "/app/cmd/api/certs/server.crt"
  path_to_keyfile: "/app/cmd/api/private/server.key"
logger:
  logger_prefix: "APP:"
  path_to_logfile: "/app/logs/log.txt"
db:
  # TODO: разобраться со строкой подключения